### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 1433020484** [niuhuan/html-comic#1]
请问一下，为什么填了代理ip也加载不出来，是得要海外ip吗，还是这app现在用不了了

**Comment by niuhuan** [comment]
一直都是需要海外网络，手机开全局，pc连本地代理软件

**Comment by 1433020484** [comment]
> 一直都是需要海外网络，手机开全局，pc连本地代理软件

我挂了梯子开了全局还是加载不出来

**Comment by 1433020484** [comment]
还有就是我想请问一下，为什么我点注册那的国际链接可以登录成功了网页版，但是app登录除了l ine1column1就是bad state呀

**Comment by niuhuan** [comment]
这个软件并不能登录

**Comment by 1433020484** [comment]
> 这个软件并不能登录
> 

我换了好几个ip，一直都显示这样，是什么原因呀![S31207-10415028_niuhuan.html.png](https://github.com/niuhuan/html-comic/assets/121925120/d4ccaa9c-c9ee-401e-b010-270a26483c69)

**Comment by 1433020484** [comment]
> 这个软件并不能登录
> 

噢噢，不好意思，我说的登录不上是jm，后来得知您没有维护了，不好意思

**Comment by niuhuan** [comment]
需要改大量的api从app接口到web接口，暂时没有时间。
